### ISSUE TITLE
launching the zebar silently 

### ISSUE THREAD

**Issue by azinsharaf** [glzr-io/zebar#47]
i am using the `start.bat` file to launch the `zebar`.  how can i launch it as a no-console application without terminal that shows the activities? 
when i launch it i have this terminal open (minimized):

![image](https://github.com/glzr-io/zebar/assets/10101468/7c15ed18-fae8-4888-9623-818826b09a97)

**Comment by pluque01** [comment]
Hey @azinsharaf 
This has also been an issue for me. As far as I know, there is no way to invoke a hidden terminal using batch or PowerShell scripts (.ps1). There is however a workaround:

* Create a VBScript file (you can just rename a .txt to .vbs) in my case `start-zebar.vbs`
* Paste the following:
```VBScript
CreateObject("Wscript.Shell").Run "powershell path_to_start.bat", 0, True
```

* Substitute `path_to_start.bat` with the full path to where you have the `start.bat` you downloaded from zebar

Now you can run this instead and it will be hidden.

**Comment by lars-berger** [comment]
@azinsharaf Does the CMD window stay open? When I'm launching the `start.cmd` script (eg. from file explorer), it opens a CMD window briefly and then closes itself. Having no CMD window show up at all can be worked around with @pluque01's suggestion of using a `.vbs` script to start instead.

@pluque01 Really cool that you discovered this - was actually debating shipping a `.vbs` script instead of a `.bat` file for this reason, but what sucks is that VBScript is officially deprecated and can't be a long-term solution. I'm not sure whether there's an alternative approach out there though.

**Comment by pluque01** [comment]
@Vernetzt that also works great! It's true that it shows the terminal for a short time, but it is not a big deal for me.

**Comment by azinsharaf** [comment]
that works great. 
The one i was using was downloaded from the release page.
@lars-berger do you think the script @Vernetzt provided can be replaced with the one in the Relases section?

the script from the release section:

```
@echo off
@REM Start hidden powershell script, which runs `zebar open bar --args ...` for every monitor.
powershell -WindowStyle hidden -Command ^
  $monitors = zebar monitors; ^
  foreach ($monitor in $monitors) { Start-Process -NoNewWindow -FilePath \"zebar\" -ArgumentList \"open bar --args $monitor\" };
  ```

**Comment by Vernetzt** [comment]
It might be better to offer it as a secondary option labeled with it's intention of opening "silently".

The main reason I say this is currently Zebar has no tray icon or `stop` command so without the default terminal window hanging around the only way to stop it would be process termination. Might be better as a opt-in choice rather than default, at least until something like a `stop` command could be implemented.

**Comment by azinsharaf** [comment]
totaly agree. I have to kill ithe process manually now.

**Comment by lars-berger** [comment]
Updated the `start.bat` script in the last couple releases to the snippet that @Vernetzt posted. LMK if there's still problems with this 👍
